qua-platform/qualibrate-app

- frontend/src/modules/GraphLibrary/components/GraphElement/GraphElement.tsx
- frontend/src/modules/GraphLibrary/components/GraphStatus/components/MeasurementElementGraph/MeasurementElementGraph.module.scss
- frontend/src/modules/GraphLibrary/context/GraphContext.tsx
Fix for https://quantum-machines.atlassian.net/jira/software/c/projects/QUAL/boards/152?assignee=63f600eb4e86f362d39b5c80&selectedIssue=QUAL-657
> Do the fetch of cytoscape graph elements before showing them

- frontend/src/modules/Nodes/context/NodesContext.tsx
Fix for: https://quantum-machines.atlassian.net/browse/QUAL-655
> Set the lastRun node status to idle when the Node page is loaded

- frontend/src/modules/GraphLibrary/GraphLibrary.module.scss
- frontend/src/modules/GraphLibrary/index.tsx
Related issue: https://quantum-machines.atlassian.net/browse/QUAL-658
> Commented out GraphSearch component from Graph library page

- backend/qualibrate_app/app.py
[QUAL-823](https://quantum-machines.atlassian.net/browse/QUAL-823)
> Change api docs url path

- frontend/src/routing/flexLayout/FlexLayoutBuilder.ts
- frontend/src/routing/flexLayout/FlexLayoutContext.tsx
Jira issue: https://quantum-machines.atlassian.net/browse/QUAL-843
> Make pages stay opened

- frontend/src/modules/Data/components/JSONEditor.tsx
- frontend/src/modules/Data/components/TimelineGraph.tsx
- frontend/src/modules/Data/index.tsx
- frontend/src/modules/GraphLibrary/components/GraphElement/GraphElement.module.scss
- frontend/src/modules/Nodes/components/Results/Results.tsx
- frontend/src/modules/Nodes/components/RunningJob/RunningJob.tsx
- frontend/src/modules/Nodes/components/StateUpdates/StateUpdateComponent.tsx
- frontend/src/modules/Nodes/components/StateUpdates/StateUpdates.module.scss
- frontend/src/modules/Nodes/components/StateUpdates/StateUpdates.tsx
Jira issue: https://quantum-machines.atlassian.net/browse/QUAL-671
> Components refactor and reorganize

- frontend/src/modules/Nodes/components/RunningJob/RunningJob.module.scss
- frontend/src/modules/Nodes/components/StateUpdates/StateUpdateComponent.tsx
Issue: https://quantum-machines.atlassian.net/browse/QUAL-876
> Fix up arrow icon pointer css

- frontend/src/modules/Nodes/components/NodeElement/NodeElement.tsx
- frontend/src/modules/Nodes/components/RunningJob/RunningJob.tsx
- frontend/src/modules/Nodes/components/StateUpdates/StateUpdateComponent.tsx
- frontend/src/modules/Nodes/components/StateUpdates/StateUpdates.tsx
- frontend/src/modules/Nodes/context/NodesContext.tsx
Jira issue: https://quantum-machines.atlassian.net/browse/QUAL-907
> Fixed updateAll button on Run calibration node page

- frontend/src/modules/GraphLibrary/components/CytoscapeGraph/CytoscapeGraph.tsx
- frontend/src/modules/GraphLibrary/components/GraphStatus/GraphStatus.tsx
Jira issue: https://quantum-machines.atlassian.net/browse/QUAL-1104
> Fix for unselecting Track latest n Graph Status page

- frontend/src/modules/GraphLibrary/components/GraphStatus/components/MeasurementElementGraph/MeasurementElementGraph.module.scss
- frontend/src/modules/GraphLibrary/components/GraphStatus/components/MeasurementElementGraph/MeasurementElementGraph.tsx
https://quantum-machines.atlassian.net/browse/QUAL-1180
> Adaptive "Active Calibration Graph" Title and Dynamic Status Indicator in MeasurementElementGraph

- frontend/src/modules/Nodes/components/NodeElement/NodeElement.tsx
- frontend/src/ui-lib/Icons/InfoIcon.tsx
https://quantum-machines.atlassian.net/jira/software/c/projects/QUAL/boards/173?assignee=712020%3A2a0fc73a-d6d7-4126-9576-6e44837c6a01&selectedIssue=QUAL-1217
> feat/Show Info tooltip in node list for description

- backend/qualibrate_app/api/core/domain/local_storage/snapshot.py
- backend/qualibrate_app/api/core/models/snapshot.py
- backend/tests/api/local_storage/test_branch.py
- backend/tests/api/local_storage/test_root.py
- backend/tests/api/local_storage/test_snapshot.py
- backend/tests/unit/test_api_core/test_domain/test_local_storage/test_snapshot.py
[QUAL-1214](https://quantum-machines.atlassian.net/browse/QUAL-1214)
> Snapshot contains parameters

- frontend/.gitignore
- frontend/src/common/ui-components/common/Page/Page.module.scss
- frontend/src/contexts/TitleBarMenuContext.tsx
- frontend/src/modules/Data/Data.module.scss
- frontend/src/modules/Data/index.tsx
- frontend/src/modules/GraphLibrary/GraphLibrary.module.scss
- frontend/src/modules/GraphLibrary/components/GraphElement/GraphElement.module.scss
- frontend/src/modules/GraphLibrary/components/GraphStatus/GraphStatus.module.scss
- frontend/src/modules/GraphLibrary/components/GraphStatus/GraphStatus.tsx
- frontend/src/modules/GraphLibrary/index.tsx
- frontend/src/modules/Nodes/NodesPage.module.scss
- frontend/src/modules/Nodes/index.tsx
- frontend/src/modules/SidebarMenu/MenuItem.tsx
- frontend/src/modules/TopbarMenu/TitleBarMenu.tsx
- frontend/src/modules/TopbarMenu/TitleBarMenuCard.tsx
- frontend/src/modules/TopbarMenu/styles/TitleBarMenu.module.scss
- frontend/src/modules/TopbarMenu/styles/TitleBarMenuCard.module.scss
- frontend/src/routing/ModulesRegistry.ts
- frontend/src/routing/flexLayout/FlexLayoutContext.tsx
- frontend/src/routing/flexLayout/FlexLayoutFactory.tsx
- frontend/src/ui-lib/layouts/MainLayout.tsx
- frontend/src/ui-lib/layouts/styles/Layout.module.scss
- frontend/tests/e2e/workflow1.test.ts
Jira issue: https://quantum-machines.atlassian.net/browse/QUAL-1126
> Added top bar tooltip

- frontend/src/modules/Data/components/JSONEditor.tsx
Currently the switching between live and final happens whenever data is received. Instead, it will now switch to live only when a "postmessage" is received.
The qua dashboard is configured such that it sends this
This logic will also be used for the graph live plot switching
> Feat/Switch between live / final when receiving a PostMessage indication

- frontend/src/modules/Nodes/context/NodesContext.tsx
Jira issue: https://quantum-machines.atlassian.net/browse/QUAL-1249
> Small fix to align the changes from the BE regarding status

- backend/qualibrate_app/api/core/domain/bases/storage.py
[QUAL-1304](https://quantum-machines.atlassian.net/browse/QUAL-1304)
> Recursively parse images from storage

- frontend/src/modules/GraphLibrary/components/GraphStatus/components/MeasurementElement/MeasurementElement.module.scss
- frontend/src/modules/GraphLibrary/components/GraphStatus/components/MeasurementElement/MeasurementElement.tsx
- frontend/src/modules/Nodes/components/NodeElement/NodeElement.module.scss
- frontend/src/modules/Nodes/components/NodeElement/NodeElement.tsx
Jira issue: https://quantum-machines.atlassian.net/browse/QUAL-1342
> Fix description tooltip on Graph Status page

- backend/qualibrate_app/app.py
- backend/qualibrate_app/config/resolvers.py
[QUAL-1315](https://quantum-machines.atlassian.net/browse/QUAL-1315)
> Optional config static path

- frontend/src/modules/TopbarMenu/TitleBarMenuCard.tsx
- frontend/src/modules/TopbarMenu/styles/TitleBarMenuCard.module.scss
https://quantum-machines.atlassian.net/jira/software/c/projects/QUAL/boards/173?assignee=712020%3A2a0fc73a-d6d7-4126-9576-6e44837c6a01&selectedIssue=QUAL-1303
> Fix/Node Status Card Layout and Text Display Issues

- frontend/src/index.tsx
- frontend/src/modules/Data/components/JSONEditor.module.scss
- frontend/src/modules/Nodes/components/Results/Results.module.scss
- frontend/src/modules/Nodes/components/RunningJob/RunningJob.module.scss
- frontend/src/modules/Nodes/index.tsx
- frontend/src/utils/api/index.ts
We need this change so Nikola wont have an issue.
P. S. Instead of having `USE_HASH_ROUTER` in the .env file, we'll have `USE_RELATIVE_PATHS`.
> Small fixes for relative paths usage

- frontend/src/modules/TopbarMenu/TitleBarNodeCard/styles/TitleBarNodeCard.module.scss
https://quantum-machines.atlassian.net/jira/software/c/projects/QUAL/boards/173?assignee=712020%3A2a0fc73a-d6d7-4126-9576-6e44837c6a01&selectedIssue=QUAL-1455
> fix/node label cut-off within node status card

- frontend/src/index.tsx
- frontend/src/modules/GraphLibrary/components/GraphStatus/GraphStatus.tsx
- frontend/src/modules/GraphLibrary/context/GraphContext.tsx
- frontend/src/modules/GraphLibrary/index.tsx
https://quantum-machines.atlassian.net/browse/QUAL-1268
> Small fix for multiple API calls causing a memory leak

- frontend/package-lock.json
- frontend/package.json
- frontend/webpack.config.js
JIRA tasks:
https://quantum-machines.atlassian.net/browse/QUAL-1471
https://quantum-machines.atlassian.net/browse/QUAL-1475
> Fix webpack and deprecated (vulnerable dependencies)

- backend/qualibrate_app/api/core/models/project.py
[QUAL-1551](https://quantum-machines.atlassian.net/browse/QUAL-1551)
> Add project config content to list

- backend/qualibrate_app/api/__main__.py
- backend/qualibrate_app/api/core/domain/bases/project.py
- backend/qualibrate_app/api/core/domain/local_storage/project.py
- backend/qualibrate_app/api/core/domain/timeline_db/project.py
- backend/qualibrate_app/api/core/models/project.py
- backend/qualibrate_app/api/routes/__init__.py
- backend/qualibrate_app/api/routes/project.py
- backend/tests/api/local_storage/fixtures/settings.py
- backend/tests/api/local_storage/test_project.py
[QUAL-1130](https://quantum-machines.atlassian.net/browse/QUAL-1130)
> Project management

- frontend/src/dev.config.ts
- frontend/src/modules/Project/index.tsx
- frontend/src/modules/TopbarMenu/ProjectTitleBar.tsx
- frontend/src/modules/TopbarMenu/TitleBarMenu.tsx
- frontend/src/modules/TopbarMenu/styles/TitleBarMenu.module.scss
- frontend/src/ui-lib/Icons/NewProjectButtonIcon.tsx
https://quantum-machines.atlassian.net/jira/software/c/projects/QUAL/boards/173?assignee=712020%3A2a0fc73a-d6d7-4126-9576-6e44837c6a01&selectedIssue=QUAL-1497
> Feat/Create New Project Button

- frontend/src/index.tsx
- frontend/src/modules/GraphLibrary/components/GraphStatus/GraphStatus.tsx
- frontend/src/modules/GraphLibrary/context/GraphContext.tsx
- frontend/src/modules/Nodes/components/NodeElement/NodeElement.tsx
- frontend/src/modules/Nodes/components/Results/Results.tsx
- frontend/src/modules/Nodes/context/NodesContext.tsx
- frontend/src/modules/Nodes/index.tsx
JIRA issues:
https://quantum-machines.atlassian.net/browse/QUAL-1578
https://quantum-machines.atlassian.net/browse/QUAL-1580
https://quantum-machines.atlassian.net/browse/QUAL-1581
> Fix for not fetching workflows on refresh

- frontend/src/modules/Project/Project.module.scss
- frontend/src/modules/Project/index.tsx
- frontend/src/modules/TopbarMenu/TitleBarMenu.tsx
Moved the "Create new Project button". Original:
Updated location
> Feat: Move the 'create new project' button
